apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: vit-app 
spec: 
  # For Scalability I have added the replica factor 2 
  replicas: 2
  selector:
    matchLabels:
      app: vit-app
  template: 
    metadata: 
      labels:
        app: vit-app
    spec: 
      containers: 
        - name: app
          image: us-central1-docker.pkg.dev/gcp-videos-451916/webreathe/vit-app:2bfea4d18948eb59d059c2502f8b742c42d8ed87
          ports: 
          - containerPort: 8000
          - containerPort: 5173
          imagePullPolicy: Always
          # Pulls the Env values from the secrets
          env:
            - name: DB_CONNECTION
              valueFrom: 
                secretKeyRef:
                  name: db-secrets
                  key: DB_CONNECTION
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
          # Resources and Limits for the Pod CPU and Memory
          # resources: 
          #   requests:
          #     memory: "512Mi"
          #     cpu: "500m"
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          # This Checks whether the application is healthy or not
          # livenessProbe:
          #   httpGet:
          #     path: /healthz 
          #     port: 8000 
          #     httpHeaders: 
          #     - name: Custom-Header 
          #       value: Awesome
          #   initialDelaySeconds: 3
          #   periodSeconds: 3 
          # This chekcs whether the application is ready or not
          # readinessProbe: 
          #   httpGet:
          #     path: /healthz
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
