apiVersion: v1 
kind: Service 
metadata: 
  name: vit-svc 
spec:  
  type: LoadBalancer
  selector:
      app: vit-app
  ports: 
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP 
      port: 5173
      targetPort: 5173
