name: Deploy to GKE

on:
  push:
    branches:
        - main

env: 
    PROJECT_ID: "gcp-videos-451916"
    CLUSTER: "webreathe"
    LOCATION: "us-central1"

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
        - name: Checkout code
          uses: actions/checkout@v2 

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            version: 'latest'
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            project_id: ${{ env.PROJECT_ID }}

        - name: Authenticate to Google Cloud 
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        - name: Authenticate Docker
          run: | 
            gcloud auth configure-docker us-central1-docker.pkg.dev
        
        - name: Build and Push Docker image 
          run: | 
            cd modules/
            IMAGE=us-central1-docker.pkg.dev/gcp-videos-451916/webreathe:${{ github.sha }}
            docker build -t $IMAGE .
            docker push $IMAGE

        - name: Set the GKE secrets.GCP_CREDENTIALS
          run: | 
            gcloud container clusters get-credentials webreathe --zone us-central1 --project ${{ env.PROJECT_ID }}

        - name: Deploy to GKE
          run: | 
            kubectl deploy kube-mysql.yaml
            kubectl deploy kube-mysql-svc.yaml