name: Deploy to GKE

on:
  push:
    branches:
        - main

env: 
    PROJECT_ID: "gcp-videos-451916"

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
        - name: Checkout code
          uses: actions/checkout@v2 

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            version: 'latest'
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            project_id: ${{ env.PROJECT_ID }}

        - name: Authenticate Docker
          run: | 
            gcloud auth configure-docker 
        
        - name: Build and Push Docker image 
          run: | 
            cd modules/
            IMAGE=gcr.io/${{ env.PROJECT_ID }}/my-app:${{ github.sha }}
            docker build -t $IMAGE .
            docker push $IMAGE