name: Deploy to GKE

on:
  push:
    branches:
        - main

env: 
    PROJECT_ID: gcp-videos-451916
    CLUSTER: webreathe
    LOCATION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
        # Pulls the latest code from the repository
        - name: Checkout code
          uses: actions/checkout@v2 

        # INstalling the Python to run Python related tasks
        - name: Set up Python
          uses: actions/setup-python@v2 
          with: 
            python-version: '3.8'
        
        #Authentication to the Google Cloud SDK
        - name: Authenticate to Google Cloud 
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

        # Setting up the Google Cloud SDK - Accessing to the GCP Project
        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ env.PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            install_components: 'gke-gcloud-auth-plugin'
            export_default_credentials: true 

        # Authenticating to the Docker
        - name: Authenticate Docker
          run: | 
            gcloud auth configure-docker us-central1-docker.pkg.dev
        
        # Build and push to the Artifacts
        # - name: Build and Push Docker image 
        #   run: | 
        #     cd modules/
        #     IMAGE=us-central1-docker.pkg.dev/gcp-videos-451916/webreathe/vit-app:${{ github.sha }}
        #     docker build -t $IMAGE .
        #     docker push $IMAGE

        # Accessing the GKE Cluster
        - name: Set the GKE secrets.GCP_CREDENTIALS
          run: | 
            gcloud container clusters get-credentials webreathe --zone us-central1 --project ${{ env.PROJECT_ID }}

        # Deploying Yaml files on the Cluster(GKE)
        - name: Deploy to GKE
          run: | 
            kubectl apply -f kube-mysql.yaml
            kubectl apply -f kube-mysql-svc.yaml
            kubectl apply -f kube-app-svc.yaml
            kubectl apply -f kube-app-secret.yaml
            kubectl apply -f kube-app.yaml